# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: book.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='book.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\nbook.proto\"\x17\n\tBookQuery\x12\n\n\x02id\x18\x01 \x01(\x05\"9\n\x04\x42ook\x12\x0e\n\x06\x61uthor\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x12\n\nbook_cover\x18\x03 \x01(\t\" \n\x0c\x42ookResponse\x12\x10\n\x08response\x18\x01 \x01(\x05\"%\n\rBooksResponse\x12\x14\n\x05\x62ooks\x18\x01 \x03(\x0b\x32\x05.Book2\x85\x01\n\rRelevantBooks\x12$\n\nSubmitBook\x12\x05.Book\x1a\r.BookResponse\"\x00\x12(\n\x08GetBooks\x12\n.BookQuery\x1a\x0e.BooksResponse\"\x00\x12$\n\nRemoveBook\x12\x05.Book\x1a\r.BookResponse\"\x00\x62\x06proto3')
)




_BOOKQUERY = _descriptor.Descriptor(
  name='BookQuery',
  full_name='BookQuery',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='BookQuery.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=14,
  serialized_end=37,
)


_BOOK = _descriptor.Descriptor(
  name='Book',
  full_name='Book',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='author', full_name='Book.author', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='title', full_name='Book.title', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='book_cover', full_name='Book.book_cover', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=96,
)


_BOOKRESPONSE = _descriptor.Descriptor(
  name='BookResponse',
  full_name='BookResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='response', full_name='BookResponse.response', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=98,
  serialized_end=130,
)


_BOOKSRESPONSE = _descriptor.Descriptor(
  name='BooksResponse',
  full_name='BooksResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='books', full_name='BooksResponse.books', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=132,
  serialized_end=169,
)

_BOOKSRESPONSE.fields_by_name['books'].message_type = _BOOK
DESCRIPTOR.message_types_by_name['BookQuery'] = _BOOKQUERY
DESCRIPTOR.message_types_by_name['Book'] = _BOOK
DESCRIPTOR.message_types_by_name['BookResponse'] = _BOOKRESPONSE
DESCRIPTOR.message_types_by_name['BooksResponse'] = _BOOKSRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BookQuery = _reflection.GeneratedProtocolMessageType('BookQuery', (_message.Message,), dict(
  DESCRIPTOR = _BOOKQUERY,
  __module__ = 'book_pb2'
  # @@protoc_insertion_point(class_scope:BookQuery)
  ))
_sym_db.RegisterMessage(BookQuery)

Book = _reflection.GeneratedProtocolMessageType('Book', (_message.Message,), dict(
  DESCRIPTOR = _BOOK,
  __module__ = 'book_pb2'
  # @@protoc_insertion_point(class_scope:Book)
  ))
_sym_db.RegisterMessage(Book)

BookResponse = _reflection.GeneratedProtocolMessageType('BookResponse', (_message.Message,), dict(
  DESCRIPTOR = _BOOKRESPONSE,
  __module__ = 'book_pb2'
  # @@protoc_insertion_point(class_scope:BookResponse)
  ))
_sym_db.RegisterMessage(BookResponse)

BooksResponse = _reflection.GeneratedProtocolMessageType('BooksResponse', (_message.Message,), dict(
  DESCRIPTOR = _BOOKSRESPONSE,
  __module__ = 'book_pb2'
  # @@protoc_insertion_point(class_scope:BooksResponse)
  ))
_sym_db.RegisterMessage(BooksResponse)



_RELEVANTBOOKS = _descriptor.ServiceDescriptor(
  name='RelevantBooks',
  full_name='RelevantBooks',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=172,
  serialized_end=305,
  methods=[
  _descriptor.MethodDescriptor(
    name='SubmitBook',
    full_name='RelevantBooks.SubmitBook',
    index=0,
    containing_service=None,
    input_type=_BOOK,
    output_type=_BOOKRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetBooks',
    full_name='RelevantBooks.GetBooks',
    index=1,
    containing_service=None,
    input_type=_BOOKQUERY,
    output_type=_BOOKSRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='RemoveBook',
    full_name='RelevantBooks.RemoveBook',
    index=2,
    containing_service=None,
    input_type=_BOOK,
    output_type=_BOOKRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_RELEVANTBOOKS)

DESCRIPTOR.services_by_name['RelevantBooks'] = _RELEVANTBOOKS

# @@protoc_insertion_point(module_scope)
